version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vue-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - moyu
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: java-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
    volumes:
      - ./logs/java:/app/logs
    networks:
      - moyu
    restart: always
    # 可选：添加健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  moyu:
    driver: bridge

volumes:
  nginx-logs:
  java-logs: 