spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://192.168.88.88:9000/
  accessKey: rVtgVoXHEzJdwf0Zf3p3
  secretKey: H8arW0q6Simqbo9wHjCMcdXLQcwQThnAWLXKWKF4
  bucketName: demo

